stations:
  - name: "EET TASAJERA"
    ip: "10.155.150.201"
    port: 502
    id: 10
    endian: "cdab" # (Word Swapped) es común
    data_type: "float32"
    pointer_address: 10000 # Dirección para leer el apuntador
    base_data_address: 700 # Dirección base para los datos
    data_registers_count: 2
  - name: "LLANOS"
    ip: "10.50.184.208"
    port: 502
    id: 2
    endian: "dcba" # (Little Endian)
    data_type: "float32"
    pointer_address: 10000 # Dirección para leer el apuntador
    base_data_address: 700 # Dirección base para los datos
    data_registers_count: 1
  - name: "YOLOMBO"
    ip: "10.156.168.116"
    port: 502
    id: 1
    endian: "cdab" # (Little Endian)
    data_type: "float32"
    pointer_address: 10000 # Dirección para leer el apuntador
    base_data_address: 700 # Dirección base para los datos
    data_registers_count: 2
  - name: "SANTO DOMINGO"
    ip: "10.155.115.46"
    port: 502
    id: 1
    endian: "cdab" # (Little Endian)
    data_type: "float32"
    pointer_address: 10000 # Dirección para leer el apuntador
    base_data_address: 700 # Dirección base para los datos
    data_registers_count: 2
  - name: "SAN VICENTE"
    ip: "10.155.249.194"
    port: 502
    id: 1
    endian: "cdab" # (Little Endian)
    data_type: "float32"
    pointer_address: 10000 # Dirección para leer el apuntador
    base_data_address: 700 # Dirección base para los datos
    data_registers_count: 2
  - name: "PARQUE DE LAS AGUAS"
    ip: "10.14.224.5"
    port: 502
    id: 1
    endian: "cdab" # (Little Endian)
    data_type: "float32"
    pointer_address: 10000 # Dirección para leer el apuntador
    base_data_address: 700 # Dirección base para los datos
    data_registers_count: 2
  - name: "NARE"
    ip: "10.14.201.3"
    port: 502
    id: 1
    endian: "cdab" # (Little Endian)
    data_type: "float32"
    pointer_address: 10000 # Dirección para leer el apuntador
    base_data_address: 700 # Dirección base para los datos
    data_registers_count: 2
  - name: "MACEO"
    ip: "10.156.148.8"
    port: 502
    id: 1
    endian: "cdab" # (Little Endian)
    data_type: "float32"
    pointer_address: 10000 # Dirección para leer el apuntador
    base_data_address: 700 # Dirección base para los datos
    data_registers_count: 2
  - name: "FELISA"
    ip: "10.155.249.193"
    port: 502
    id: 1
    endian: "cdab" # (Little Endian)
    data_type: "float32"
    pointer_address: 10000 # Dirección para leer el apuntador
    base_data_address: 700 # Dirección base para los datos
    data_registers_count: 2
