stations:
  - name: "Estación 1"
    ip: "10.155.150.201"
    port: 502
    id: 10
    endian: "cdab" # (Word Swapped) es común
    data_type: "float32"
    pointer_address: 10000 # Dirección para leer el apuntador
    base_data_address: 700 # Dirección base para los datos
    data_registers_count: 2
  - name: "Estación 2"
    ip: "10.50.184.208"
    port: 502
    id: 2
    endian: "dcba" # (Little Endian)
    data_type: "float32"
    pointer_address: 10000 # Dirección para leer el apuntador
    base_data_address: 700 # Dirección base para los datos
    data_registers_count: 1
